/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.realtime.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2766183310193083130L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.realtime.avro\",\"fields\":[{\"name\":\"customer_id\",\"type\":\"string\"},{\"name\":\"service_area_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"booking_time\",\"type\":[\"null\",\"string\"]},{\"name\":\"merchant_category\",\"type\":[\"null\",\"string\"],\"default\":\"NONE\"},{\"name\":\"merchant_sub_category\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"collection\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"merchant_id\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"status_name\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"voucher_id\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"merchant_latitude\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"merchant_longitude\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"booking_destination_latitude\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"booking_destination_longitude\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"booking_destination_s2id\",\"type\":[\"null\",\"string\"],\"default\":\"\"},{\"name\":\"booking_pickup_to_destination_distance_km\",\"type\":\"double\"},{\"name\":\"normalized_gmv\",\"type\":\"double\"},{\"name\":\"cbv\",\"type\":\"float\"},{\"name\":\"item_total_cnt\",\"type\":\"float\"},{\"name\":\"item_unique_cnt\",\"type\":\"float\"},{\"name\":\"dynamic_surge_factor\",\"type\":\"float\"},{\"name\":\"payment_method_name\",\"type\":[\"null\",\"string\"],\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<Order>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Order to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Order from a ByteBuffer. */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence customer_id;
  @Deprecated public java.lang.CharSequence service_area_name;
  @Deprecated public java.lang.CharSequence booking_time;
  @Deprecated public java.lang.CharSequence merchant_category;
  @Deprecated public java.lang.CharSequence merchant_sub_category;
  @Deprecated public java.lang.CharSequence collection;
  @Deprecated public java.lang.CharSequence merchant_id;
  @Deprecated public java.lang.CharSequence status_name;
  @Deprecated public java.lang.CharSequence voucher_id;
  @Deprecated public java.lang.CharSequence merchant_latitude;
  @Deprecated public java.lang.CharSequence merchant_longitude;
  @Deprecated public java.lang.CharSequence booking_destination_latitude;
  @Deprecated public java.lang.CharSequence booking_destination_longitude;
  @Deprecated public java.lang.CharSequence booking_destination_s2id;
  @Deprecated public double booking_pickup_to_destination_distance_km;
  @Deprecated public double normalized_gmv;
  @Deprecated public float cbv;
  @Deprecated public float item_total_cnt;
  @Deprecated public float item_unique_cnt;
  @Deprecated public float dynamic_surge_factor;
  @Deprecated public java.lang.CharSequence payment_method_name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param customer_id The new value for customer_id
   * @param service_area_name The new value for service_area_name
   * @param booking_time The new value for booking_time
   * @param merchant_category The new value for merchant_category
   * @param merchant_sub_category The new value for merchant_sub_category
   * @param collection The new value for collection
   * @param merchant_id The new value for merchant_id
   * @param status_name The new value for status_name
   * @param voucher_id The new value for voucher_id
   * @param merchant_latitude The new value for merchant_latitude
   * @param merchant_longitude The new value for merchant_longitude
   * @param booking_destination_latitude The new value for booking_destination_latitude
   * @param booking_destination_longitude The new value for booking_destination_longitude
   * @param booking_destination_s2id The new value for booking_destination_s2id
   * @param booking_pickup_to_destination_distance_km The new value for booking_pickup_to_destination_distance_km
   * @param normalized_gmv The new value for normalized_gmv
   * @param cbv The new value for cbv
   * @param item_total_cnt The new value for item_total_cnt
   * @param item_unique_cnt The new value for item_unique_cnt
   * @param dynamic_surge_factor The new value for dynamic_surge_factor
   * @param payment_method_name The new value for payment_method_name
   */
  public Order(java.lang.CharSequence customer_id, java.lang.CharSequence service_area_name, java.lang.CharSequence booking_time, java.lang.CharSequence merchant_category, java.lang.CharSequence merchant_sub_category, java.lang.CharSequence collection, java.lang.CharSequence merchant_id, java.lang.CharSequence status_name, java.lang.CharSequence voucher_id, java.lang.CharSequence merchant_latitude, java.lang.CharSequence merchant_longitude, java.lang.CharSequence booking_destination_latitude, java.lang.CharSequence booking_destination_longitude, java.lang.CharSequence booking_destination_s2id, java.lang.Double booking_pickup_to_destination_distance_km, java.lang.Double normalized_gmv, java.lang.Float cbv, java.lang.Float item_total_cnt, java.lang.Float item_unique_cnt, java.lang.Float dynamic_surge_factor, java.lang.CharSequence payment_method_name) {
    this.customer_id = customer_id;
    this.service_area_name = service_area_name;
    this.booking_time = booking_time;
    this.merchant_category = merchant_category;
    this.merchant_sub_category = merchant_sub_category;
    this.collection = collection;
    this.merchant_id = merchant_id;
    this.status_name = status_name;
    this.voucher_id = voucher_id;
    this.merchant_latitude = merchant_latitude;
    this.merchant_longitude = merchant_longitude;
    this.booking_destination_latitude = booking_destination_latitude;
    this.booking_destination_longitude = booking_destination_longitude;
    this.booking_destination_s2id = booking_destination_s2id;
    this.booking_pickup_to_destination_distance_km = booking_pickup_to_destination_distance_km;
    this.normalized_gmv = normalized_gmv;
    this.cbv = cbv;
    this.item_total_cnt = item_total_cnt;
    this.item_unique_cnt = item_unique_cnt;
    this.dynamic_surge_factor = dynamic_surge_factor;
    this.payment_method_name = payment_method_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customer_id;
    case 1: return service_area_name;
    case 2: return booking_time;
    case 3: return merchant_category;
    case 4: return merchant_sub_category;
    case 5: return collection;
    case 6: return merchant_id;
    case 7: return status_name;
    case 8: return voucher_id;
    case 9: return merchant_latitude;
    case 10: return merchant_longitude;
    case 11: return booking_destination_latitude;
    case 12: return booking_destination_longitude;
    case 13: return booking_destination_s2id;
    case 14: return booking_pickup_to_destination_distance_km;
    case 15: return normalized_gmv;
    case 16: return cbv;
    case 17: return item_total_cnt;
    case 18: return item_unique_cnt;
    case 19: return dynamic_surge_factor;
    case 20: return payment_method_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customer_id = (java.lang.CharSequence)value$; break;
    case 1: service_area_name = (java.lang.CharSequence)value$; break;
    case 2: booking_time = (java.lang.CharSequence)value$; break;
    case 3: merchant_category = (java.lang.CharSequence)value$; break;
    case 4: merchant_sub_category = (java.lang.CharSequence)value$; break;
    case 5: collection = (java.lang.CharSequence)value$; break;
    case 6: merchant_id = (java.lang.CharSequence)value$; break;
    case 7: status_name = (java.lang.CharSequence)value$; break;
    case 8: voucher_id = (java.lang.CharSequence)value$; break;
    case 9: merchant_latitude = (java.lang.CharSequence)value$; break;
    case 10: merchant_longitude = (java.lang.CharSequence)value$; break;
    case 11: booking_destination_latitude = (java.lang.CharSequence)value$; break;
    case 12: booking_destination_longitude = (java.lang.CharSequence)value$; break;
    case 13: booking_destination_s2id = (java.lang.CharSequence)value$; break;
    case 14: booking_pickup_to_destination_distance_km = (java.lang.Double)value$; break;
    case 15: normalized_gmv = (java.lang.Double)value$; break;
    case 16: cbv = (java.lang.Float)value$; break;
    case 17: item_total_cnt = (java.lang.Float)value$; break;
    case 18: item_unique_cnt = (java.lang.Float)value$; break;
    case 19: dynamic_surge_factor = (java.lang.Float)value$; break;
    case 20: payment_method_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customer_id' field.
   * @return The value of the 'customer_id' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customer_id;
  }

  /**
   * Sets the value of the 'customer_id' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customer_id = value;
  }

  /**
   * Gets the value of the 'service_area_name' field.
   * @return The value of the 'service_area_name' field.
   */
  public java.lang.CharSequence getServiceAreaName() {
    return service_area_name;
  }

  /**
   * Sets the value of the 'service_area_name' field.
   * @param value the value to set.
   */
  public void setServiceAreaName(java.lang.CharSequence value) {
    this.service_area_name = value;
  }

  /**
   * Gets the value of the 'booking_time' field.
   * @return The value of the 'booking_time' field.
   */
  public java.lang.CharSequence getBookingTime() {
    return booking_time;
  }

  /**
   * Sets the value of the 'booking_time' field.
   * @param value the value to set.
   */
  public void setBookingTime(java.lang.CharSequence value) {
    this.booking_time = value;
  }

  /**
   * Gets the value of the 'merchant_category' field.
   * @return The value of the 'merchant_category' field.
   */
  public java.lang.CharSequence getMerchantCategory() {
    return merchant_category;
  }

  /**
   * Sets the value of the 'merchant_category' field.
   * @param value the value to set.
   */
  public void setMerchantCategory(java.lang.CharSequence value) {
    this.merchant_category = value;
  }

  /**
   * Gets the value of the 'merchant_sub_category' field.
   * @return The value of the 'merchant_sub_category' field.
   */
  public java.lang.CharSequence getMerchantSubCategory() {
    return merchant_sub_category;
  }

  /**
   * Sets the value of the 'merchant_sub_category' field.
   * @param value the value to set.
   */
  public void setMerchantSubCategory(java.lang.CharSequence value) {
    this.merchant_sub_category = value;
  }

  /**
   * Gets the value of the 'collection' field.
   * @return The value of the 'collection' field.
   */
  public java.lang.CharSequence getCollection() {
    return collection;
  }

  /**
   * Sets the value of the 'collection' field.
   * @param value the value to set.
   */
  public void setCollection(java.lang.CharSequence value) {
    this.collection = value;
  }

  /**
   * Gets the value of the 'merchant_id' field.
   * @return The value of the 'merchant_id' field.
   */
  public java.lang.CharSequence getMerchantId() {
    return merchant_id;
  }

  /**
   * Sets the value of the 'merchant_id' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.CharSequence value) {
    this.merchant_id = value;
  }

  /**
   * Gets the value of the 'status_name' field.
   * @return The value of the 'status_name' field.
   */
  public java.lang.CharSequence getStatusName() {
    return status_name;
  }

  /**
   * Sets the value of the 'status_name' field.
   * @param value the value to set.
   */
  public void setStatusName(java.lang.CharSequence value) {
    this.status_name = value;
  }

  /**
   * Gets the value of the 'voucher_id' field.
   * @return The value of the 'voucher_id' field.
   */
  public java.lang.CharSequence getVoucherId() {
    return voucher_id;
  }

  /**
   * Sets the value of the 'voucher_id' field.
   * @param value the value to set.
   */
  public void setVoucherId(java.lang.CharSequence value) {
    this.voucher_id = value;
  }

  /**
   * Gets the value of the 'merchant_latitude' field.
   * @return The value of the 'merchant_latitude' field.
   */
  public java.lang.CharSequence getMerchantLatitude() {
    return merchant_latitude;
  }

  /**
   * Sets the value of the 'merchant_latitude' field.
   * @param value the value to set.
   */
  public void setMerchantLatitude(java.lang.CharSequence value) {
    this.merchant_latitude = value;
  }

  /**
   * Gets the value of the 'merchant_longitude' field.
   * @return The value of the 'merchant_longitude' field.
   */
  public java.lang.CharSequence getMerchantLongitude() {
    return merchant_longitude;
  }

  /**
   * Sets the value of the 'merchant_longitude' field.
   * @param value the value to set.
   */
  public void setMerchantLongitude(java.lang.CharSequence value) {
    this.merchant_longitude = value;
  }

  /**
   * Gets the value of the 'booking_destination_latitude' field.
   * @return The value of the 'booking_destination_latitude' field.
   */
  public java.lang.CharSequence getBookingDestinationLatitude() {
    return booking_destination_latitude;
  }

  /**
   * Sets the value of the 'booking_destination_latitude' field.
   * @param value the value to set.
   */
  public void setBookingDestinationLatitude(java.lang.CharSequence value) {
    this.booking_destination_latitude = value;
  }

  /**
   * Gets the value of the 'booking_destination_longitude' field.
   * @return The value of the 'booking_destination_longitude' field.
   */
  public java.lang.CharSequence getBookingDestinationLongitude() {
    return booking_destination_longitude;
  }

  /**
   * Sets the value of the 'booking_destination_longitude' field.
   * @param value the value to set.
   */
  public void setBookingDestinationLongitude(java.lang.CharSequence value) {
    this.booking_destination_longitude = value;
  }

  /**
   * Gets the value of the 'booking_destination_s2id' field.
   * @return The value of the 'booking_destination_s2id' field.
   */
  public java.lang.CharSequence getBookingDestinationS2id() {
    return booking_destination_s2id;
  }

  /**
   * Sets the value of the 'booking_destination_s2id' field.
   * @param value the value to set.
   */
  public void setBookingDestinationS2id(java.lang.CharSequence value) {
    this.booking_destination_s2id = value;
  }

  /**
   * Gets the value of the 'booking_pickup_to_destination_distance_km' field.
   * @return The value of the 'booking_pickup_to_destination_distance_km' field.
   */
  public java.lang.Double getBookingPickupToDestinationDistanceKm() {
    return booking_pickup_to_destination_distance_km;
  }

  /**
   * Sets the value of the 'booking_pickup_to_destination_distance_km' field.
   * @param value the value to set.
   */
  public void setBookingPickupToDestinationDistanceKm(java.lang.Double value) {
    this.booking_pickup_to_destination_distance_km = value;
  }

  /**
   * Gets the value of the 'normalized_gmv' field.
   * @return The value of the 'normalized_gmv' field.
   */
  public java.lang.Double getNormalizedGmv() {
    return normalized_gmv;
  }

  /**
   * Sets the value of the 'normalized_gmv' field.
   * @param value the value to set.
   */
  public void setNormalizedGmv(java.lang.Double value) {
    this.normalized_gmv = value;
  }

  /**
   * Gets the value of the 'cbv' field.
   * @return The value of the 'cbv' field.
   */
  public java.lang.Float getCbv() {
    return cbv;
  }

  /**
   * Sets the value of the 'cbv' field.
   * @param value the value to set.
   */
  public void setCbv(java.lang.Float value) {
    this.cbv = value;
  }

  /**
   * Gets the value of the 'item_total_cnt' field.
   * @return The value of the 'item_total_cnt' field.
   */
  public java.lang.Float getItemTotalCnt() {
    return item_total_cnt;
  }

  /**
   * Sets the value of the 'item_total_cnt' field.
   * @param value the value to set.
   */
  public void setItemTotalCnt(java.lang.Float value) {
    this.item_total_cnt = value;
  }

  /**
   * Gets the value of the 'item_unique_cnt' field.
   * @return The value of the 'item_unique_cnt' field.
   */
  public java.lang.Float getItemUniqueCnt() {
    return item_unique_cnt;
  }

  /**
   * Sets the value of the 'item_unique_cnt' field.
   * @param value the value to set.
   */
  public void setItemUniqueCnt(java.lang.Float value) {
    this.item_unique_cnt = value;
  }

  /**
   * Gets the value of the 'dynamic_surge_factor' field.
   * @return The value of the 'dynamic_surge_factor' field.
   */
  public java.lang.Float getDynamicSurgeFactor() {
    return dynamic_surge_factor;
  }

  /**
   * Sets the value of the 'dynamic_surge_factor' field.
   * @param value the value to set.
   */
  public void setDynamicSurgeFactor(java.lang.Float value) {
    this.dynamic_surge_factor = value;
  }

  /**
   * Gets the value of the 'payment_method_name' field.
   * @return The value of the 'payment_method_name' field.
   */
  public java.lang.CharSequence getPaymentMethodName() {
    return payment_method_name;
  }

  /**
   * Sets the value of the 'payment_method_name' field.
   * @param value the value to set.
   */
  public void setPaymentMethodName(java.lang.CharSequence value) {
    this.payment_method_name = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.realtime.avro.Order.Builder newBuilder() {
    return new com.realtime.avro.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.realtime.avro.Order.Builder newBuilder(com.realtime.avro.Order.Builder other) {
    return new com.realtime.avro.Order.Builder(other);
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.realtime.avro.Order.Builder newBuilder(com.realtime.avro.Order other) {
    return new com.realtime.avro.Order.Builder(other);
  }

  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private java.lang.CharSequence customer_id;
    private java.lang.CharSequence service_area_name;
    private java.lang.CharSequence booking_time;
    private java.lang.CharSequence merchant_category;
    private java.lang.CharSequence merchant_sub_category;
    private java.lang.CharSequence collection;
    private java.lang.CharSequence merchant_id;
    private java.lang.CharSequence status_name;
    private java.lang.CharSequence voucher_id;
    private java.lang.CharSequence merchant_latitude;
    private java.lang.CharSequence merchant_longitude;
    private java.lang.CharSequence booking_destination_latitude;
    private java.lang.CharSequence booking_destination_longitude;
    private java.lang.CharSequence booking_destination_s2id;
    private double booking_pickup_to_destination_distance_km;
    private double normalized_gmv;
    private float cbv;
    private float item_total_cnt;
    private float item_unique_cnt;
    private float dynamic_surge_factor;
    private java.lang.CharSequence payment_method_name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.realtime.avro.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[0].schema(), other.customer_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.service_area_name)) {
        this.service_area_name = data().deepCopy(fields()[1].schema(), other.service_area_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.booking_time)) {
        this.booking_time = data().deepCopy(fields()[2].schema(), other.booking_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.merchant_category)) {
        this.merchant_category = data().deepCopy(fields()[3].schema(), other.merchant_category);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.merchant_sub_category)) {
        this.merchant_sub_category = data().deepCopy(fields()[4].schema(), other.merchant_sub_category);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.collection)) {
        this.collection = data().deepCopy(fields()[5].schema(), other.collection);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[6].schema(), other.merchant_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status_name)) {
        this.status_name = data().deepCopy(fields()[7].schema(), other.status_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.voucher_id)) {
        this.voucher_id = data().deepCopy(fields()[8].schema(), other.voucher_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.merchant_latitude)) {
        this.merchant_latitude = data().deepCopy(fields()[9].schema(), other.merchant_latitude);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.merchant_longitude)) {
        this.merchant_longitude = data().deepCopy(fields()[10].schema(), other.merchant_longitude);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.booking_destination_latitude)) {
        this.booking_destination_latitude = data().deepCopy(fields()[11].schema(), other.booking_destination_latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.booking_destination_longitude)) {
        this.booking_destination_longitude = data().deepCopy(fields()[12].schema(), other.booking_destination_longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.booking_destination_s2id)) {
        this.booking_destination_s2id = data().deepCopy(fields()[13].schema(), other.booking_destination_s2id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.booking_pickup_to_destination_distance_km)) {
        this.booking_pickup_to_destination_distance_km = data().deepCopy(fields()[14].schema(), other.booking_pickup_to_destination_distance_km);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.normalized_gmv)) {
        this.normalized_gmv = data().deepCopy(fields()[15].schema(), other.normalized_gmv);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.cbv)) {
        this.cbv = data().deepCopy(fields()[16].schema(), other.cbv);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.item_total_cnt)) {
        this.item_total_cnt = data().deepCopy(fields()[17].schema(), other.item_total_cnt);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.item_unique_cnt)) {
        this.item_unique_cnt = data().deepCopy(fields()[18].schema(), other.item_unique_cnt);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.dynamic_surge_factor)) {
        this.dynamic_surge_factor = data().deepCopy(fields()[19].schema(), other.dynamic_surge_factor);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.payment_method_name)) {
        this.payment_method_name = data().deepCopy(fields()[20].schema(), other.payment_method_name);
        fieldSetFlags()[20] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.realtime.avro.Order other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.customer_id)) {
        this.customer_id = data().deepCopy(fields()[0].schema(), other.customer_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.service_area_name)) {
        this.service_area_name = data().deepCopy(fields()[1].schema(), other.service_area_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.booking_time)) {
        this.booking_time = data().deepCopy(fields()[2].schema(), other.booking_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.merchant_category)) {
        this.merchant_category = data().deepCopy(fields()[3].schema(), other.merchant_category);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.merchant_sub_category)) {
        this.merchant_sub_category = data().deepCopy(fields()[4].schema(), other.merchant_sub_category);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.collection)) {
        this.collection = data().deepCopy(fields()[5].schema(), other.collection);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[6].schema(), other.merchant_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status_name)) {
        this.status_name = data().deepCopy(fields()[7].schema(), other.status_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.voucher_id)) {
        this.voucher_id = data().deepCopy(fields()[8].schema(), other.voucher_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.merchant_latitude)) {
        this.merchant_latitude = data().deepCopy(fields()[9].schema(), other.merchant_latitude);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.merchant_longitude)) {
        this.merchant_longitude = data().deepCopy(fields()[10].schema(), other.merchant_longitude);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.booking_destination_latitude)) {
        this.booking_destination_latitude = data().deepCopy(fields()[11].schema(), other.booking_destination_latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.booking_destination_longitude)) {
        this.booking_destination_longitude = data().deepCopy(fields()[12].schema(), other.booking_destination_longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.booking_destination_s2id)) {
        this.booking_destination_s2id = data().deepCopy(fields()[13].schema(), other.booking_destination_s2id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.booking_pickup_to_destination_distance_km)) {
        this.booking_pickup_to_destination_distance_km = data().deepCopy(fields()[14].schema(), other.booking_pickup_to_destination_distance_km);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.normalized_gmv)) {
        this.normalized_gmv = data().deepCopy(fields()[15].schema(), other.normalized_gmv);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.cbv)) {
        this.cbv = data().deepCopy(fields()[16].schema(), other.cbv);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.item_total_cnt)) {
        this.item_total_cnt = data().deepCopy(fields()[17].schema(), other.item_total_cnt);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.item_unique_cnt)) {
        this.item_unique_cnt = data().deepCopy(fields()[18].schema(), other.item_unique_cnt);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.dynamic_surge_factor)) {
        this.dynamic_surge_factor = data().deepCopy(fields()[19].schema(), other.dynamic_surge_factor);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.payment_method_name)) {
        this.payment_method_name = data().deepCopy(fields()[20].schema(), other.payment_method_name);
        fieldSetFlags()[20] = true;
      }
    }

    /**
      * Gets the value of the 'customer_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customer_id;
    }

    /**
      * Sets the value of the 'customer_id' field.
      * @param value The value of 'customer_id'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.customer_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_id' field has been set.
      * @return True if the 'customer_id' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customer_id' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearCustomerId() {
      customer_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'service_area_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceAreaName() {
      return service_area_name;
    }

    /**
      * Sets the value of the 'service_area_name' field.
      * @param value The value of 'service_area_name'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setServiceAreaName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.service_area_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'service_area_name' field has been set.
      * @return True if the 'service_area_name' field has been set, false otherwise.
      */
    public boolean hasServiceAreaName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'service_area_name' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearServiceAreaName() {
      service_area_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'booking_time' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookingTime() {
      return booking_time;
    }

    /**
      * Sets the value of the 'booking_time' field.
      * @param value The value of 'booking_time'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setBookingTime(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.booking_time = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'booking_time' field has been set.
      * @return True if the 'booking_time' field has been set, false otherwise.
      */
    public boolean hasBookingTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'booking_time' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearBookingTime() {
      booking_time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_category' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantCategory() {
      return merchant_category;
    }

    /**
      * Sets the value of the 'merchant_category' field.
      * @param value The value of 'merchant_category'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setMerchantCategory(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.merchant_category = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_category' field has been set.
      * @return True if the 'merchant_category' field has been set, false otherwise.
      */
    public boolean hasMerchantCategory() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'merchant_category' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearMerchantCategory() {
      merchant_category = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_sub_category' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantSubCategory() {
      return merchant_sub_category;
    }

    /**
      * Sets the value of the 'merchant_sub_category' field.
      * @param value The value of 'merchant_sub_category'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setMerchantSubCategory(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.merchant_sub_category = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_sub_category' field has been set.
      * @return True if the 'merchant_sub_category' field has been set, false otherwise.
      */
    public boolean hasMerchantSubCategory() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'merchant_sub_category' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearMerchantSubCategory() {
      merchant_sub_category = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'collection' field.
      * @return The value.
      */
    public java.lang.CharSequence getCollection() {
      return collection;
    }

    /**
      * Sets the value of the 'collection' field.
      * @param value The value of 'collection'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setCollection(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.collection = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'collection' field has been set.
      * @return True if the 'collection' field has been set, false otherwise.
      */
    public boolean hasCollection() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'collection' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearCollection() {
      collection = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantId() {
      return merchant_id;
    }

    /**
      * Sets the value of the 'merchant_id' field.
      * @param value The value of 'merchant_id'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setMerchantId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.merchant_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_id' field has been set.
      * @return True if the 'merchant_id' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'merchant_id' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearMerchantId() {
      merchant_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusName() {
      return status_name;
    }

    /**
      * Sets the value of the 'status_name' field.
      * @param value The value of 'status_name'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setStatusName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.status_name = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'status_name' field has been set.
      * @return True if the 'status_name' field has been set, false otherwise.
      */
    public boolean hasStatusName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'status_name' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearStatusName() {
      status_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'voucher_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getVoucherId() {
      return voucher_id;
    }

    /**
      * Sets the value of the 'voucher_id' field.
      * @param value The value of 'voucher_id'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setVoucherId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.voucher_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'voucher_id' field has been set.
      * @return True if the 'voucher_id' field has been set, false otherwise.
      */
    public boolean hasVoucherId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'voucher_id' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearVoucherId() {
      voucher_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantLatitude() {
      return merchant_latitude;
    }

    /**
      * Sets the value of the 'merchant_latitude' field.
      * @param value The value of 'merchant_latitude'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setMerchantLatitude(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.merchant_latitude = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_latitude' field has been set.
      * @return True if the 'merchant_latitude' field has been set, false otherwise.
      */
    public boolean hasMerchantLatitude() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'merchant_latitude' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearMerchantLatitude() {
      merchant_latitude = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantLongitude() {
      return merchant_longitude;
    }

    /**
      * Sets the value of the 'merchant_longitude' field.
      * @param value The value of 'merchant_longitude'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setMerchantLongitude(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.merchant_longitude = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_longitude' field has been set.
      * @return True if the 'merchant_longitude' field has been set, false otherwise.
      */
    public boolean hasMerchantLongitude() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'merchant_longitude' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearMerchantLongitude() {
      merchant_longitude = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'booking_destination_latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookingDestinationLatitude() {
      return booking_destination_latitude;
    }

    /**
      * Sets the value of the 'booking_destination_latitude' field.
      * @param value The value of 'booking_destination_latitude'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setBookingDestinationLatitude(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.booking_destination_latitude = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'booking_destination_latitude' field has been set.
      * @return True if the 'booking_destination_latitude' field has been set, false otherwise.
      */
    public boolean hasBookingDestinationLatitude() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'booking_destination_latitude' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearBookingDestinationLatitude() {
      booking_destination_latitude = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'booking_destination_longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookingDestinationLongitude() {
      return booking_destination_longitude;
    }

    /**
      * Sets the value of the 'booking_destination_longitude' field.
      * @param value The value of 'booking_destination_longitude'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setBookingDestinationLongitude(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.booking_destination_longitude = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'booking_destination_longitude' field has been set.
      * @return True if the 'booking_destination_longitude' field has been set, false otherwise.
      */
    public boolean hasBookingDestinationLongitude() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'booking_destination_longitude' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearBookingDestinationLongitude() {
      booking_destination_longitude = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'booking_destination_s2id' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookingDestinationS2id() {
      return booking_destination_s2id;
    }

    /**
      * Sets the value of the 'booking_destination_s2id' field.
      * @param value The value of 'booking_destination_s2id'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setBookingDestinationS2id(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.booking_destination_s2id = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'booking_destination_s2id' field has been set.
      * @return True if the 'booking_destination_s2id' field has been set, false otherwise.
      */
    public boolean hasBookingDestinationS2id() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'booking_destination_s2id' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearBookingDestinationS2id() {
      booking_destination_s2id = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'booking_pickup_to_destination_distance_km' field.
      * @return The value.
      */
    public java.lang.Double getBookingPickupToDestinationDistanceKm() {
      return booking_pickup_to_destination_distance_km;
    }

    /**
      * Sets the value of the 'booking_pickup_to_destination_distance_km' field.
      * @param value The value of 'booking_pickup_to_destination_distance_km'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setBookingPickupToDestinationDistanceKm(double value) {
      validate(fields()[14], value);
      this.booking_pickup_to_destination_distance_km = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'booking_pickup_to_destination_distance_km' field has been set.
      * @return True if the 'booking_pickup_to_destination_distance_km' field has been set, false otherwise.
      */
    public boolean hasBookingPickupToDestinationDistanceKm() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'booking_pickup_to_destination_distance_km' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearBookingPickupToDestinationDistanceKm() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'normalized_gmv' field.
      * @return The value.
      */
    public java.lang.Double getNormalizedGmv() {
      return normalized_gmv;
    }

    /**
      * Sets the value of the 'normalized_gmv' field.
      * @param value The value of 'normalized_gmv'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setNormalizedGmv(double value) {
      validate(fields()[15], value);
      this.normalized_gmv = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'normalized_gmv' field has been set.
      * @return True if the 'normalized_gmv' field has been set, false otherwise.
      */
    public boolean hasNormalizedGmv() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'normalized_gmv' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearNormalizedGmv() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'cbv' field.
      * @return The value.
      */
    public java.lang.Float getCbv() {
      return cbv;
    }

    /**
      * Sets the value of the 'cbv' field.
      * @param value The value of 'cbv'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setCbv(float value) {
      validate(fields()[16], value);
      this.cbv = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'cbv' field has been set.
      * @return True if the 'cbv' field has been set, false otherwise.
      */
    public boolean hasCbv() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'cbv' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearCbv() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'item_total_cnt' field.
      * @return The value.
      */
    public java.lang.Float getItemTotalCnt() {
      return item_total_cnt;
    }

    /**
      * Sets the value of the 'item_total_cnt' field.
      * @param value The value of 'item_total_cnt'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setItemTotalCnt(float value) {
      validate(fields()[17], value);
      this.item_total_cnt = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'item_total_cnt' field has been set.
      * @return True if the 'item_total_cnt' field has been set, false otherwise.
      */
    public boolean hasItemTotalCnt() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'item_total_cnt' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearItemTotalCnt() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'item_unique_cnt' field.
      * @return The value.
      */
    public java.lang.Float getItemUniqueCnt() {
      return item_unique_cnt;
    }

    /**
      * Sets the value of the 'item_unique_cnt' field.
      * @param value The value of 'item_unique_cnt'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setItemUniqueCnt(float value) {
      validate(fields()[18], value);
      this.item_unique_cnt = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'item_unique_cnt' field has been set.
      * @return True if the 'item_unique_cnt' field has been set, false otherwise.
      */
    public boolean hasItemUniqueCnt() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'item_unique_cnt' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearItemUniqueCnt() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'dynamic_surge_factor' field.
      * @return The value.
      */
    public java.lang.Float getDynamicSurgeFactor() {
      return dynamic_surge_factor;
    }

    /**
      * Sets the value of the 'dynamic_surge_factor' field.
      * @param value The value of 'dynamic_surge_factor'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setDynamicSurgeFactor(float value) {
      validate(fields()[19], value);
      this.dynamic_surge_factor = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'dynamic_surge_factor' field has been set.
      * @return True if the 'dynamic_surge_factor' field has been set, false otherwise.
      */
    public boolean hasDynamicSurgeFactor() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'dynamic_surge_factor' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearDynamicSurgeFactor() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_method_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentMethodName() {
      return payment_method_name;
    }

    /**
      * Sets the value of the 'payment_method_name' field.
      * @param value The value of 'payment_method_name'.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder setPaymentMethodName(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.payment_method_name = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_method_name' field has been set.
      * @return True if the 'payment_method_name' field has been set, false otherwise.
      */
    public boolean hasPaymentMethodName() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'payment_method_name' field.
      * @return This builder.
      */
    public com.realtime.avro.Order.Builder clearPaymentMethodName() {
      payment_method_name = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.customer_id = fieldSetFlags()[0] ? this.customer_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.service_area_name = fieldSetFlags()[1] ? this.service_area_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.booking_time = fieldSetFlags()[2] ? this.booking_time : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.merchant_category = fieldSetFlags()[3] ? this.merchant_category : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.merchant_sub_category = fieldSetFlags()[4] ? this.merchant_sub_category : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.collection = fieldSetFlags()[5] ? this.collection : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.merchant_id = fieldSetFlags()[6] ? this.merchant_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.status_name = fieldSetFlags()[7] ? this.status_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.voucher_id = fieldSetFlags()[8] ? this.voucher_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.merchant_latitude = fieldSetFlags()[9] ? this.merchant_latitude : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.merchant_longitude = fieldSetFlags()[10] ? this.merchant_longitude : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.booking_destination_latitude = fieldSetFlags()[11] ? this.booking_destination_latitude : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.booking_destination_longitude = fieldSetFlags()[12] ? this.booking_destination_longitude : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.booking_destination_s2id = fieldSetFlags()[13] ? this.booking_destination_s2id : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.booking_pickup_to_destination_distance_km = fieldSetFlags()[14] ? this.booking_pickup_to_destination_distance_km : (java.lang.Double) defaultValue(fields()[14]);
        record.normalized_gmv = fieldSetFlags()[15] ? this.normalized_gmv : (java.lang.Double) defaultValue(fields()[15]);
        record.cbv = fieldSetFlags()[16] ? this.cbv : (java.lang.Float) defaultValue(fields()[16]);
        record.item_total_cnt = fieldSetFlags()[17] ? this.item_total_cnt : (java.lang.Float) defaultValue(fields()[17]);
        record.item_unique_cnt = fieldSetFlags()[18] ? this.item_unique_cnt : (java.lang.Float) defaultValue(fields()[18]);
        record.dynamic_surge_factor = fieldSetFlags()[19] ? this.dynamic_surge_factor : (java.lang.Float) defaultValue(fields()[19]);
        record.payment_method_name = fieldSetFlags()[20] ? this.payment_method_name : (java.lang.CharSequence) defaultValue(fields()[20]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
